/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecibosRouteImport } from './routes/recibos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GruposIndexRouteImport } from './routes/grupos.index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as GruposIdRouteImport } from './routes/grupos.$id'
import { Route as EventosIdRouteImport } from './routes/eventos.$id'
import { Route as GruposIdIndexRouteImport } from './routes/grupos.$id.index'
import { Route as GruposIdPagamentosRouteImport } from './routes/grupos.$id.pagamentos'
import { Route as GruposIdFarolRouteImport } from './routes/grupos.$id.farol'
import { Route as GruposIdServosIndexRouteImport } from './routes/grupos.$id.servos.index'
import { Route as GruposIdServosServoIdRouteImport } from './routes/grupos.$id.servos.$servoId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecibosRoute = RecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposIndexRoute = GruposIndexRouteImport.update({
  id: '/grupos/',
  path: '/grupos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposIdRoute = GruposIdRouteImport.update({
  id: '/grupos/$id',
  path: '/grupos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIdRoute = EventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposIdIndexRoute = GruposIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GruposIdRoute,
} as any)
const GruposIdPagamentosRoute = GruposIdPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => GruposIdRoute,
} as any)
const GruposIdFarolRoute = GruposIdFarolRouteImport.update({
  id: '/farol',
  path: '/farol',
  getParentRoute: () => GruposIdRoute,
} as any)
const GruposIdServosIndexRoute = GruposIdServosIndexRouteImport.update({
  id: '/servos/',
  path: '/servos/',
  getParentRoute: () => GruposIdRoute,
} as any)
const GruposIdServosServoIdRoute = GruposIdServosServoIdRouteImport.update({
  id: '/servos/$servoId',
  path: '/servos/$servoId',
  getParentRoute: () => GruposIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/recibos': typeof RecibosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/eventos/$id': typeof EventosIdRoute
  '/grupos/$id': typeof GruposIdRouteWithChildren
  '/eventos/': typeof EventosIndexRoute
  '/grupos/': typeof GruposIndexRoute
  '/grupos/$id/farol': typeof GruposIdFarolRoute
  '/grupos/$id/pagamentos': typeof GruposIdPagamentosRoute
  '/grupos/$id/': typeof GruposIdIndexRoute
  '/grupos/$id/servos/$servoId': typeof GruposIdServosServoIdRoute
  '/grupos/$id/servos/': typeof GruposIdServosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/recibos': typeof RecibosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/eventos/$id': typeof EventosIdRoute
  '/eventos': typeof EventosIndexRoute
  '/grupos': typeof GruposIndexRoute
  '/grupos/$id/farol': typeof GruposIdFarolRoute
  '/grupos/$id/pagamentos': typeof GruposIdPagamentosRoute
  '/grupos/$id': typeof GruposIdIndexRoute
  '/grupos/$id/servos/$servoId': typeof GruposIdServosServoIdRoute
  '/grupos/$id/servos': typeof GruposIdServosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/recibos': typeof RecibosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/eventos/$id': typeof EventosIdRoute
  '/grupos/$id': typeof GruposIdRouteWithChildren
  '/eventos/': typeof EventosIndexRoute
  '/grupos/': typeof GruposIndexRoute
  '/grupos/$id/farol': typeof GruposIdFarolRoute
  '/grupos/$id/pagamentos': typeof GruposIdPagamentosRoute
  '/grupos/$id/': typeof GruposIdIndexRoute
  '/grupos/$id/servos/$servoId': typeof GruposIdServosServoIdRoute
  '/grupos/$id/servos/': typeof GruposIdServosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/dashboard'
    | '/recibos'
    | '/reset-password'
    | '/eventos/$id'
    | '/grupos/$id'
    | '/eventos/'
    | '/grupos/'
    | '/grupos/$id/farol'
    | '/grupos/$id/pagamentos'
    | '/grupos/$id/'
    | '/grupos/$id/servos/$servoId'
    | '/grupos/$id/servos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/dashboard'
    | '/recibos'
    | '/reset-password'
    | '/eventos/$id'
    | '/eventos'
    | '/grupos'
    | '/grupos/$id/farol'
    | '/grupos/$id/pagamentos'
    | '/grupos/$id'
    | '/grupos/$id/servos/$servoId'
    | '/grupos/$id/servos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/dashboard'
    | '/recibos'
    | '/reset-password'
    | '/eventos/$id'
    | '/grupos/$id'
    | '/eventos/'
    | '/grupos/'
    | '/grupos/$id/farol'
    | '/grupos/$id/pagamentos'
    | '/grupos/$id/'
    | '/grupos/$id/servos/$servoId'
    | '/grupos/$id/servos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  RecibosRoute: typeof RecibosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EventosIdRoute: typeof EventosIdRoute
  GruposIdRoute: typeof GruposIdRouteWithChildren
  EventosIndexRoute: typeof EventosIndexRoute
  GruposIndexRoute: typeof GruposIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibos': {
      id: '/recibos'
      path: '/recibos'
      fullPath: '/recibos'
      preLoaderRoute: typeof RecibosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/': {
      id: '/grupos/'
      path: '/grupos'
      fullPath: '/grupos/'
      preLoaderRoute: typeof GruposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/$id': {
      id: '/grupos/$id'
      path: '/grupos/$id'
      fullPath: '/grupos/$id'
      preLoaderRoute: typeof GruposIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$id': {
      id: '/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof EventosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/$id/': {
      id: '/grupos/$id/'
      path: '/'
      fullPath: '/grupos/$id/'
      preLoaderRoute: typeof GruposIdIndexRouteImport
      parentRoute: typeof GruposIdRoute
    }
    '/grupos/$id/pagamentos': {
      id: '/grupos/$id/pagamentos'
      path: '/pagamentos'
      fullPath: '/grupos/$id/pagamentos'
      preLoaderRoute: typeof GruposIdPagamentosRouteImport
      parentRoute: typeof GruposIdRoute
    }
    '/grupos/$id/farol': {
      id: '/grupos/$id/farol'
      path: '/farol'
      fullPath: '/grupos/$id/farol'
      preLoaderRoute: typeof GruposIdFarolRouteImport
      parentRoute: typeof GruposIdRoute
    }
    '/grupos/$id/servos/': {
      id: '/grupos/$id/servos/'
      path: '/servos'
      fullPath: '/grupos/$id/servos/'
      preLoaderRoute: typeof GruposIdServosIndexRouteImport
      parentRoute: typeof GruposIdRoute
    }
    '/grupos/$id/servos/$servoId': {
      id: '/grupos/$id/servos/$servoId'
      path: '/servos/$servoId'
      fullPath: '/grupos/$id/servos/$servoId'
      preLoaderRoute: typeof GruposIdServosServoIdRouteImport
      parentRoute: typeof GruposIdRoute
    }
  }
}

interface GruposIdRouteChildren {
  GruposIdFarolRoute: typeof GruposIdFarolRoute
  GruposIdPagamentosRoute: typeof GruposIdPagamentosRoute
  GruposIdIndexRoute: typeof GruposIdIndexRoute
  GruposIdServosServoIdRoute: typeof GruposIdServosServoIdRoute
  GruposIdServosIndexRoute: typeof GruposIdServosIndexRoute
}

const GruposIdRouteChildren: GruposIdRouteChildren = {
  GruposIdFarolRoute: GruposIdFarolRoute,
  GruposIdPagamentosRoute: GruposIdPagamentosRoute,
  GruposIdIndexRoute: GruposIdIndexRoute,
  GruposIdServosServoIdRoute: GruposIdServosServoIdRoute,
  GruposIdServosIndexRoute: GruposIdServosIndexRoute,
}

const GruposIdRouteWithChildren = GruposIdRoute._addFileChildren(
  GruposIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  RecibosRoute: RecibosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EventosIdRoute: EventosIdRoute,
  GruposIdRoute: GruposIdRouteWithChildren,
  EventosIndexRoute: EventosIndexRoute,
  GruposIndexRoute: GruposIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
